### ISSUE TITLE
Improve CAOS Error Messages

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#43]
An Error caused by Syntax, or other Issues, should also contain the Input CAOS commands, This is not a Usefull Error Message!:

```
Expected numeric rvalue at token 'e'
 [targ agnt {@}e sets va00 "" outs "{" loop namn va00   ...
RETRY: WARNING: Expecting value: line 1 column 1 (char 0), Retrying in 3 seconds...
Expected numeric rvalue at token 'e'
 [targ agnt {@}e sets va00 "" outs "{" loop namn va00   ...
RETRY: WARNING: Expecting value: line 1 column 1 (char 0), Retrying in 6 seconds...
Expected numeric rvalue at token 'e'
 [targ agnt {@}e sets va00 "" outs "{" loop namn va00   ...
RETRY: WARNING: Expecting value: line 1 column 1 (char 0), Retrying in 12 seconds...
Expected numeric rvalue at token 'e'
 [targ agnt {@}e sets va00 "" outs "{" loop namn va00   ...
RETRY: WARNING: Expecting value: line 1 column 1 (char 0), Retrying in 24 seconds...
Expected numeric rvalue at token 'e'
 [targ agnt {@}e sets va00 "" outs "{" loop namn va00   ...
ERROR: Expecting value: line 1 column 1 (char 0)
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "AlbianWarpPythonClient.py", line 452, in rtdma_send_handler
  File "AlbianWarpPythonClient.py", line 447, in rtdma_send_handler
  File "util.py", line 40, in f_retry
  File "AlbianWarpPythonClient.py", line 429, in send_rtdma
  File "CaosEvolution\Agent.py", line 99, in dict
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

DEBUG: dma_send_handler thread ended
DEBUG: creature_download_handler thread ended
DEBUG: contactlist_handler thread ended
DEBUG: dma_receive_handler thread ended
DEBUG: creature_upload_handler thread ended
Press Enter to Exit...
´´´

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
